### ISSUE TITLE
Team formation

### ISSUE THREAD

**Issue by raelga** [kcdspain/spain-2022#1]
## What

We'll need to fill the following core roles + shadows to get the ball rolling. The current list of role responsibilities is just a suggestion based on the last KCD Spain 2021. 

Each team will decide on sub-team roles and responsibilities (ie - marketing lead will determine if a writer is needed) based on the direction of the event.

**Shadows** for the roles do not need to have event experience but should be ok with taking a **Lead** role within the next 12 months of events.

## How

The Guide from the Kubernetes Community Days website:

https://kubernetescommunitydays.org/organizing/

The checklist:

[Kubernetes Community Days Conference Action Items and Assignments](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=0)

#### Responsibilities

- Project management
- CNCF interactions
- SIG-Contribex interactions
- Sponsorship (if applies)

##### Time required

~3-4 hours each week, with some extra work during the early stages.

#### Responsibilities

- Define event tracks and schedule
- Talk introduction / moderation
- Call for proposals ingestion / Speakers

##### Time required

~4 hours each week, mid term to handle the call for papers evaluations and the schedule / tracks creation.

#### Responsibilities

- Website
- Social media / Community management
- Call for proposals form
- Swag (if applies)

##### Time required

~6 hours each week, pretty consisten work: early stages to start talking about the event, mid term to raise awareness for the call for papers, near the event date to publicity the event and the talks, during the event to create momentun in the social networks.

#### Responsibilities

- Bevy platform setup
- Streaming production
- Recordings edit / publication
- Technical support

##### Time required

~4 hours each week, mostly when the event date approaches. The week of the event, it almost require full time dedication.

## Team

Teams and roles will be decided during the early days of planning after summer, as we still don't the kind of event that will end occurring.

| Role               | Lead                                 | Shadow                                                                                                                             | Notes |
| ------------------ | ------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------- | ----- |
| Event coordination | @raelga                              | @aagea <br> @borjareinares <br> @pfuentesg <br> @javierprovecho <br> @mario-ezquerro <br> @92nqb <br> @JorTurFer   <br> @pasqualet <br>  @agonzalezro  |       |
| Content            |       @jorgermp                                | @vthot4  <br> @aagea <br> @raelga <br> @borjareinares <br> @xoanmm <br> @javierprovecho <br> @92nqb <br> @JorTurFer        <br>  @mvazquezc <br> @pasqualet <br>  @agonzalezro       |       |
| Marketing          | @92nqb  / @raelga                 |  <br> @rcarpio-hbo <br> @vjjmiras  <br>  @pasqualet                                                                                     |       |
| Multimedia         | @javierprovecho / @mario-ezquerro | @mario-ezquerro <br> @jorgermp <br> @raelga                                                                                                |       |

**Comment by vestival** [comment]
I volunteer myself to collaborate in the multimedia team :D

**Comment by raelga** [comment]
Buenas! 

Empezamos a poner las cosas en funcionamiento, la primera reunión será la semana que viene. 

Si quieres participar, apúntate en el Doodle:

https://doodle.com/meeting/participate/id/dwjEPBJb

**Comment by mario-ezquerro** [comment]
Estamos in....

**Comment by vthot4** [comment]
Me gustaría ayudar en la parte de Content

**Comment by raelga** [comment]
Me gustaría participar como Lead de Event coordination o Marketing, y como Shadow de Content.

**Comment by aagea** [comment]
Me gustaría colaborar como Shadow en event coordination y content

**Comment by rcarpio-hbo** [comment]
Hola,
Me gustaría participar como Shadow en Marketing y Content

**Comment by borjareinares** [comment]
Me gustaría colaborar como shadow en Event coordination y Content

**Comment by xoanmm** [comment]
Me gustaría colaborar como shadow en Content

**Comment by vjjmiras** [comment]
Me gustaría colaborar como shadow en Marketing

**Comment by pfuentesg** [comment]
Me gustaría colaborar como shadow en Event coordination

**Comment by javierprovecho** [comment]
Me gustaría colaborar como:
- lead en Multimedia
- shadow en Event coordination y Content

**Comment by mario-ezquerro** [comment]
Me gustaría colaborar como:

lead or shadow en Multimedia
shadow en Event coordination y Content

**Comment by 92nqb** [comment]
Hola a todos, me gustaría colaborar como:

- Lead or shadow en Marketing
- Shadow en Event coordination y Content

**Comment by JorTurFer** [comment]
Hey!
Yo me sumaría como `shadow` en `event coordination `y `content`

**Comment by raelga** [comment]
Nos vemos en unas horas en la reunión semanal :)

https://go.rael.dev/kcd2022-meetings

**Comment by pasqualet** [comment]
Hola! Me gustaría colaborar como:

- Shadow en Marketing
- Shadow en Event coordination
- Shadow en Content

**Comment by raelga** [comment]
| Role               | Lead                                 | Shadow                                                                                                                             | Notes |
| ------------------ | ------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------- | ----- |
| Event coordination | @raelga                              | @aagea <br> @borjareinares <br> @pfuentesg <br> @javierprovecho <br> @mario-ezquerro <br> @92nqb <br> @JorTurFer   <br> @pasqualet |       |
| Content            |       @jorgermp                                | @vthot4  <br> @aagea <br> @raelga <br> @borjareinares <br> @xoanmm <br> @javierprovecho <br> @92nqb <br> @JorTurFer        <br>  @mvazquezc  @pasqualet       |       |
| Marketing          | @92nqb  / @raelga                 |  @davazkz  <br> @rcarpio-hbo <br> @vjjmiras  <br>   @pasqualet                                                                                     |       |
| Multimedia         | @javierprovecho / @mario-ezquerro | @mario-ezquerro <br> @jorgermp <br> @raelga                                                                                                |       |

**Comment by mvazquezc** [comment]
Hola, me gustaría colaborar como shadow en Content.

**Comment by raelga** [comment]
Cerramos los equipos!

**Comment by davazkz** [comment]
Si aun se necesita, despues de hablar con Alvaro Agea me propongo como shadow para apoyo en el area de Marketing
