### ISSUE TITLE
¡Participa!

### ISSUE THREAD

**Issue by raelga** [kcdspain/spain-2022#2]
Si te gustaría participar en el próximo KCD Spain 2022 pero no sabes por dónde empezar, deja un comentario en este issue y nos pondremos en contacto cuando empiece la planificación del evento.

**Comment by vestival** [comment]
Yo me apunto! 👍

**Comment by roxcarpio** [comment]
Hola!! 
Estaría encantada de ayudar en la siguiente edición🤘🏻

**Comment by JorTurFer** [comment]
Me apunto a un bombardeo, contad conmigo!! :)

**Comment by raelga** [comment]
Buenas! 

Empezamos a poner las cosas en funcionamiento, la primera reunión será la semana que viene. 

Si quieres participar, apúntate en el Doodle:

https://doodle.com/meeting/participate/id/dwjEPBJb

**Comment by mario-ezquerro** [comment]
Me apunto ....

**Comment by roxcarpio** [comment]
> Buenas!
> 
> Empezamos a poner las cosas en funcionamiento, la primera reunión será la semana que viene.
> 
> Si quieres participar, apúntate en el Doodle:
> 
> https://doodle.com/meeting/participate/id/dwjEPBJb

Rellenado 🤟🏻

**Comment by pfuentesg** [comment]
Me apunto!

**Comment by mvazquezc** [comment]
Si puedo ayudar en cualquier cosa, contad conmigo!

**Comment by javierprovecho** [comment]
Buenas, podéis contar conmigo para la parte multimedia, como el año pasado.

EDIT: por temas de agenda, no puedo asistir a la primera reunión en cualquiera de las fechas propuestas.

**Comment by jorgermp** [comment]
Yo no voy a poder asistir a esta reunión, pero contad conmigo igual que el año pasado para la parte de contenido.

**Comment by david-caro** [comment]
Yo estoy interesado también!

**Comment by raelga** [comment]
La primera reunión será el próximo [Jueves 23, a las 11:00 AM](https://calendar.google.com/event?action=TEMPLATE&tmeid=cWwxZGJlamg1anFtbXBqc2JrNDJodW1rNDlfMjAyMjA2MjNUMDkwMDAwWiBjXzN2cjFibW02MWd0M3Q2MzI3YW9xZTNwMWQwQGc&tmsrc=c_3vr1bmm61gt3t6327aoqe3p1d0%40group.calendar.google.com&scp=ALL).

**Comment by borjareinares** [comment]
Buenas! Yo también me animo a colaborar en KCD, puedo aportar la experiencia de organizar NSSpain en todo lo que se pueda. Intentaré acudir a la reunión de hoy.

**Comment by xoanmm** [comment]
Me apunto a echar una mano!

**Comment by vthot4** [comment]
Me apunto a ayudar en lo que se pueda

**Comment by aagea** [comment]
Contad conmigo para lo que se necesite.

**Comment by JorTurFer** [comment]
✋

**Comment by raelga** [comment]
Ya se ha llevado a acabo la primera reunión 🎉 

Las notas de la reunión están disponibles: https://go.rael.dev/kcd2022-meetings

El único action item para la semana que viene dejar un comentario http://go.rael.dev/kcd2022-team con el Role en el que queréis participar y con qué implicación, Lead o Shadow.
